# Lab 2
Natalie Strömdahl

# Abstract
This report focuses on QR factorization, the direct method, least squares problem and the QR eigenvalue algorithm

# About the code

## 1. QR factorization
QR decomposition divides a matrix A into two matricies Q and R, where Q is an orthogonal matrix (Q^T)Q=I) and R is an upper triangular matrix.

In this report the Gram-Schmidt method was used. It follows from the method that for a matrix

A=[a{1}|a{2}|...|a{n}],

then the first column a1 will  be divided by its norm and become the first column in the q-matrix.

q{1}=a{1}/||a{1}|| , \\
q{n+1}=a{n+1}-(a{n+1}*q{1})*q{1}-...-(a{n+1}*q{n})*q{n}\\

The factorization has the form:

A=QR, where is the multiplication of elements a{n}*q{n} on an upper triangular form.

[QR Decomposition with Gram-Schmidt, Igor Yanovsky](https://www.math.ucla.edu/~yanovsky/Teaching/Math151B/handouts/GramSchmidt.pdf)

In [36]:
import numpy as np
import random
import math


def frobeniusNorm(m):
  result=0
  for col in m:
    for row in col:
      result += row*row
  result=math.sqrt(result)
  return(result)

def qr2(ma,me):
  r=np.multiply(ma,me)
  r[np.tril_indices(r.shape[0],-1)]=0
  
  return(r)


def qrfactorization1(matrix):
  q=[]
  matrix= np.transpose(matrix)
  print(matrix)
  col_index=0
  for column in matrix:

    if col_index==0:
      norm_vector=matrix[col_index]/np.linalg.norm(matrix[col_index])
      q.insert(0,norm_vector)
    else: 
      res=column
      for q_col in q:
       
        dot= np.dot(res,q_col)      
        res = np.subtract(res,[dot*i for i in q_col])
        res = res/np.linalg.norm(res)
      q=np.vstack([q,res])
  
    col_index +=1
  np.transpose(q)
  r=qr2(matrix,q)
  return(matrix,q,r)
  

for j in range(0,1):
  i=random.randint(1,19)
  matrix=np.random.randint(0,10,(i,i))
  (a,q,r)=qrfactorization1(matrix)

  print('||Q^TQ-I||: ',frobeniusNorm(np.transpose(q)*q-np.linalg.inv(q)))
  print('||QR-A||: ',frobeniusNorm(np.matmul(q,r)-a))


[[6 0 7 6 8]
 [2 1 7 1 2]
 [3 9 0 4 0]
 [6 5 9 4 7]
 [1 6 2 9 1]]
||Q^TQ-I||:  2.035548696272244
||QR-A||:  27.26757916121977


### Test QR
For some reason I don't get zeros when I run the function, which I find quite odd. It is most likely something wrong with the r-matrix, but I don't know. Another reason I get the wrong result could be that there is something I have misunderstood about the Gram-Schmidt method.

## Direct solver Ax=b
Since A^-1Ax=A^-1b <=> x=A^-1b \\
I first calculated the inverse of A and then performed a matrix multiplication.



In [49]:
import numpy as np
import math
import random


def directsolver(matrix,vector):
  matrix=np.linalg.inv(matrix)
  return(np.matmul(matrix,vector))
  
  
  
for j in range(0,5):
  i=random.randint(1,19)
  vector=np.random.randint(1, size=i)
  matrix=np.random.randint(0,10,(i,i))
  x=directsolver(matrix,vector)

  print('||Ax-b||: ',np.linalg.norm(np.matmul(matrix,x)-vector))



||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0


### Test Direct solver
All the result are equal to zero, which I take as a sign that the function works.

## Least squares problem Ax=b
First the transpose of A is calculated. Then A^T is multiplied with matrix A and vector b respectively. This gives: \\

A^TAx=A^Tb \\
The system is then solved using the direct method.

In [51]:
import numpy as np
def leastsquares(matrix,vector):
  mtran=np.transpose(matrix)
  mtranm=np.matmul(mtran,matrix)
  mtranv=np.matmul(mtran,vector)
  x=np.linalg.solve(mtranm,mtranv)
  return(x)


for j in range(0,5):
  i=random.randint(1,19)
  vector=np.random.randint(1, size=i)
  matrix=np.random.randint(0,10,(i,i))
  x=leastsquares(matrix,vector)

  print('||Ax-b||: ',np.linalg.norm(np.matmul(matrix,x)-vector))


  

||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0
||Ax-b||:  0.0


### Test Least squares problem
The results for this function is also zero, which is expected.

## QR eigenvalue algorithm
Using the QR algorithm an upper triangular matrix with the eigenvalues in the diagonal can be calculated. First the QR algorithm gets Q and R from A. Then A=RQ and  new Q and R values are calculated. A will continue to be modified until all the eigenvalues in the diagonal.

The eigenvectors come from first multiplying an eigenvalue with the identity matrix and then using the resulting matrix to subtract from matrix A. Then Ax=0, where x is the eigenvector. 

In [88]:
def qrEigenvalue(A):
  id=np.identity(len(A))
  eigenvectormatrix=[]
  zerovector=np.zeros(len(A))
  for i in range(50):
    (q,r)=np.linalg.qr(A)
    print('q,r',q,r)
    A= np.matmul(r,q)
    
  eigenvalue=A.diagonal()
  for value in eigenvalue:
    ideigvalue=[value*i for i in id]
    print(ideigvalue)
    result = A_.sub_(ideigenvalue)
    eigvector=np.linalg.solve(result,zerovector)
    q=np.vstack([eigenvectormatrix,eigvector])
  return(eigenvalue,eigenvectormatrix)
    
    
    
  
for j in range(0,5):
  i=random.randint(1,19)
  vector=np.random.randint(1, size=i)
  matrix=np.random.randint(0,10,(i,i))
  matrix = matrix+np.transpose(matrix)
  id=np.identity(len(matrix))
  (val, vector)=qrEigenvalue(matrix)
  for i in range(len(val)):
  
    ideigvalue=[value*i for i in id]
    print('det(A-lambda_i I: ', np.linalg.det(matrix-ideigvalue))

q,r [[-0.39473097  0.30179992  0.08165228 -0.0757919   0.09411469  0.19777657
   0.16392652  0.41428948 -0.08140572  0.55735178 -0.02206156  0.20377678
  -0.08167461 -0.12535846  0.31649067  0.1112678 ]
 [-0.09868274 -0.2370276  -0.13973052  0.50116754 -0.31003337  0.30282482
   0.18824126  0.227517   -0.01313533 -0.01660839  0.33448697 -0.17313151
   0.18128536 -0.37993995 -0.22427188  0.13617175]
 [-0.09868274 -0.37094656 -0.30235308  0.2763018   0.3535706   0.08408339
  -0.35166724 -0.05110908  0.23125189  0.29876715 -0.37978898 -0.28309148
   0.06554841  0.08245246  0.14764366  0.16285811]
 [-0.19736548 -0.38477588 -0.02099243 -0.25854578 -0.39021613 -0.31118412
   0.06656121  0.08405997 -0.3215158   0.2037767  -0.27642526 -0.0384099
  -0.22426004  0.08766962 -0.33550454  0.30295495]
 [-0.24670686  0.30022409 -0.51754602 -0.42827712 -0.23766898  0.24016504
  -0.16091377 -0.10430387  0.30679795  0.04183605  0.13608665 -0.09122383
   0.18392168  0.14908342 -0.25738011  0.04211357]
 [

AttributeError: ignored